name: Secrets workflow


on:
  pull_request:
    branches: ["main"]
  

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest
    steps:
      - name: echo environment variable
        run: echo The job name is ${{ secrets.SECRET_API_KEY }} "$API_CSPROJ_PATH"
