name: Secrets workflow


on:
  pull_request:
    branches: ["main"]
  

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variable
        run: echo The job name is $JOB_NAME "$API_CSPROJ_PATH"
  new_job:
    name: New job
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "New_job"

    steps:
      - name: echo environment variable
        run: echo The job name is $JOB_NAME "$API_CSPROJ_PATH"
